// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-clipboard at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoClipboard from "expo-clipboard"

export const ClipboardPasteButton: typeof ExpoClipboard.ClipboardPasteButton =
  ExpoClipboard.ClipboardPasteButton
export const ContentType: typeof ExpoClipboard.ContentType = ExpoClipboard.ContentType
export const StringFormat: typeof ExpoClipboard.StringFormat = ExpoClipboard.StringFormat
export const addClipboardListener: typeof ExpoClipboard.addClipboardListener =
  ExpoClipboard.addClipboardListener
export const getImageAsync: typeof ExpoClipboard.getImageAsync = ExpoClipboard.getImageAsync
export const getStringAsync: typeof ExpoClipboard.getStringAsync = ExpoClipboard.getStringAsync
export const getUrlAsync: typeof ExpoClipboard.getUrlAsync = ExpoClipboard.getUrlAsync
export const hasImageAsync: typeof ExpoClipboard.hasImageAsync = ExpoClipboard.hasImageAsync
export const hasStringAsync: typeof ExpoClipboard.hasStringAsync = ExpoClipboard.hasStringAsync
export const hasUrlAsync: typeof ExpoClipboard.hasUrlAsync = ExpoClipboard.hasUrlAsync
export const isPasteButtonAvailable: typeof ExpoClipboard.isPasteButtonAvailable =
  ExpoClipboard.isPasteButtonAvailable
export const removeClipboardListener: typeof ExpoClipboard.removeClipboardListener =
  ExpoClipboard.removeClipboardListener
export const setImageAsync: (
  base64Image: string,
  options?: import("./Clipboard.js").SetImageOptions,
) => Promise<void> = ExpoClipboard.setImageAsync
export const setStringAsync: (
  text: string,
  options?: import("./Clipboard.js").SetStringOptions,
) => Promise<boolean> = ExpoClipboard.setStringAsync
export const setUrlAsync: typeof ExpoClipboard.setUrlAsync = ExpoClipboard.setUrlAsync

export type AcceptedContentType = ExpoClipboard.AcceptedContentType
export type ClipboardEvent = ExpoClipboard.ClipboardEvent
export type ClipboardImage = ExpoClipboard.ClipboardImage
export type ClipboardPasteButtonProps = ExpoClipboard.ClipboardPasteButtonProps
export type ContentType = ExpoClipboard.ContentType
export type CornerStyleType = ExpoClipboard.CornerStyleType
export type DisplayModeType = ExpoClipboard.DisplayModeType
export type GetImageOptions = ExpoClipboard.GetImageOptions
export type GetStringOptions = ExpoClipboard.GetStringOptions
export type ImagePasteEvent = ExpoClipboard.ImagePasteEvent
export type PasteEventPayload = ExpoClipboard.PasteEventPayload
export type SetImageAndroidOptions = import("./Clipboard.js").SetImageAndroidOptions
export type SetImageOptions = import("./Clipboard.js").SetImageOptions
export type SetStringAndroidOptions = import("./Clipboard.js").SetStringAndroidOptions
export type SetStringOptions = import("./Clipboard.js").SetStringOptions
export type StringFormat = ExpoClipboard.StringFormat
export type Subscription = ExpoClipboard.Subscription
export type TextPasteEvent = ExpoClipboard.TextPasteEvent
