// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-network at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoNetwork from "expo-network"

export const NetworkStateType: typeof ExpoNetwork.NetworkStateType = ExpoNetwork.NetworkStateType
export const addNetworkStateListener: typeof ExpoNetwork.addNetworkStateListener =
  ExpoNetwork.addNetworkStateListener
export const getIpAddressAsync: typeof ExpoNetwork.getIpAddressAsync = ExpoNetwork.getIpAddressAsync
export const getNetworkStateAsync: typeof ExpoNetwork.getNetworkStateAsync =
  ExpoNetwork.getNetworkStateAsync
export const isAirplaneModeEnabledAsync: typeof ExpoNetwork.isAirplaneModeEnabledAsync =
  ExpoNetwork.isAirplaneModeEnabledAsync
export const useNetworkState: typeof ExpoNetwork.useNetworkState = ExpoNetwork.useNetworkState

export type NetworkState = ExpoNetwork.NetworkState
export type NetworkStateEvent = ExpoNetwork.NetworkStateEvent
export type NetworkStateType = ExpoNetwork.NetworkStateType
