// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-network at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoNetwork from "expo-network"

export const NetworkStateType = ExpoNetwork.NetworkStateType
export const addNetworkStateListener = ExpoNetwork.addNetworkStateListener
export const getIpAddressAsync = ExpoNetwork.getIpAddressAsync
export const getNetworkStateAsync = ExpoNetwork.getNetworkStateAsync
export const isAirplaneModeEnabledAsync = ExpoNetwork.isAirplaneModeEnabledAsync
export const useNetworkState = ExpoNetwork.useNetworkState

export type NetworkState = ExpoNetwork.NetworkState
export type NetworkStateEvent = ExpoNetwork.NetworkStateEvent
export type NetworkStateType = ExpoNetwork.NetworkStateType
