// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-background-task at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoBackgroundTask from "expo-background-task"

export const BackgroundTaskResult: typeof ExpoBackgroundTask.BackgroundTaskResult =
  ExpoBackgroundTask.BackgroundTaskResult
export const BackgroundTaskStatus: typeof ExpoBackgroundTask.BackgroundTaskStatus =
  ExpoBackgroundTask.BackgroundTaskStatus
export const addExpirationListener: typeof ExpoBackgroundTask.addExpirationListener =
  ExpoBackgroundTask.addExpirationListener
export const getStatusAsync: typeof ExpoBackgroundTask.getStatusAsync =
  ExpoBackgroundTask.getStatusAsync
export const registerTaskAsync: typeof ExpoBackgroundTask.registerTaskAsync =
  ExpoBackgroundTask.registerTaskAsync
export const triggerTaskWorkerForTestingAsync: typeof ExpoBackgroundTask.triggerTaskWorkerForTestingAsync =
  ExpoBackgroundTask.triggerTaskWorkerForTestingAsync
export const unregisterTaskAsync: typeof ExpoBackgroundTask.unregisterTaskAsync =
  ExpoBackgroundTask.unregisterTaskAsync

export type BackgroundTaskOptions = ExpoBackgroundTask.BackgroundTaskOptions
export type BackgroundTaskResult = ExpoBackgroundTask.BackgroundTaskResult
export type BackgroundTaskStatus = ExpoBackgroundTask.BackgroundTaskStatus
