import * as FileSystem from "effect/FileSystem"
import * as Data from "effect/Data"
import * as Effect from "effect/Effect"
import { decodeCapabilitySpec, type CapabilitySpec } from "@effect-expo/core/CapabilitySpec"
import { readGeneratedArtifact, writeGeneratedArtifact } from "./GeneratedArtifact.ts"

const networkSpecPath = "packages/network/src/capabilities/network.json"
const networkOutputPath = "packages/network/src/generated/Network.ts"
const networkCapabilityOutputPath = "packages/catalog/src/generated/NetworkCapability.ts"

/** A parse failure before the closed CapabilitySpec Schema can be applied. */

class CapabilitySpecJsonError extends Data.TaggedError("CapabilitySpecJsonError")<{
  readonly cause: unknown
}> {}

class GeneratedArtifactOutOfDate extends Data.TaggedError("GeneratedArtifactOutOfDate")<{
  readonly paths: ReadonlyArray<string>
}> {}

const readSpec = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem
  const source = yield* fs.readFileString(networkSpecPath)
  const json = yield* Effect.try({
    try: () => JSON.parse(source) as unknown,
    catch: (cause) => new CapabilitySpecJsonError({ cause })
  })
  return yield* decodeCapabilitySpec(json)
})

const operationType = (operation: CapabilitySpec["operations"][number]): string => {
  const constructor = operation.kind === "effect" ? "Effect.Effect" : "Stream.Stream"
  return `${constructor}<${operation.success}, ${operation.error}>`
}

const renderComment = (lines: ReadonlyArray<string>): string =>
  ["/**", ...lines.map((line) => (line.length === 0 ? " *" : ` * ${line}`)), " */"].join("\n")

const platformName = {
  android: "Android",
  ios: "iOS",
  web: "Web"
} as const

const renderOperation = (operation: CapabilitySpec["operations"][number]): string => {
  const documentation = renderComment([
    operation.documentation.summary,
    ...(operation.documentation.failures.length === 0
      ? []
      : [
          "",
          "Failure channel:",
          ...operation.documentation.failures.map((failure) => `- ${failure}`)
        ])
  ])

  return `${documentation
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n")}
  readonly ${operation.name}: ${operationType(operation)}`
}

export const renderNetwork = (spec: CapabilitySpec): string => {
  const types = Array.from(
    new Set(spec.operations.flatMap((operation) => [operation.error, operation.success]))
  ).sort()
  const operations = spec.operations.map(renderOperation).join("\n\n")
  const serviceDocumentation = renderComment([
    spec.documentation.summary,
    "",
    ...spec.documentation.details.flatMap((detail) => [detail, ""]),
    "Platform behavior:",
    ...spec.documentation.platforms.map(
      ({ behavior, name }) => `- ${platformName[name]}: ${behavior}`
    ),
    "",
    "@example",
    "```ts",
    'import { Effect } from "effect"',
    'import { Network } from "@effect-expo/network"',
    "",
    "const program = Effect.gen(function* () {",
    "  const network = yield* Network",
    "  return yield* network.current",
    "})",
    "```",
    "",
    `@category ${spec.documentation.category}`,
    `@since ${spec.documentation.since}`
  ])

  return `${renderComment([
    `Effect-native ${spec.service} capability generated from its closed specification.`,
    "",
    `@since ${spec.documentation.since}`
  ])}
// This file is generated by \`effect-expo generate\`. Do not edit it by hand.
// Package: @effect-expo/network.

import * as Context from "effect/Context"
import type * as Effect from "effect/Effect"
import type * as Stream from "effect/Stream"
import type { ${types.join(", ")} } from "../contracts/NetworkContract.ts"

${serviceDocumentation}
export interface ${spec.service} {
${operations}
}

${renderComment([
  `Service tag for the Effect-native ${spec.service} capability.`,
  "",
  `@category ${spec.documentation.category}`,
  `@since ${spec.documentation.since}`
])}
export const ${spec.service}: Context.Service<${spec.service}, ${spec.service}> = Context.Service("@effect-expo/${spec.id}")
`
}

const platformCoverage = (
  platforms: ReadonlyArray<"android" | "ios" | "web">,
  covered: "missing" | "unverified"
) => ({
  ios: platforms.includes("ios") ? covered : "not-applicable",
  android: platforms.includes("android") ? covered : "not-applicable",
  web: platforms.includes("web") ? covered : "not-applicable"
})

export const renderNetworkCapability = (spec: CapabilitySpec): string => {
  const implemented = spec.operations.map((operation) => ({
    upstream: operation.upstream,
    effect: operation.name,
    kind: operation.kind === "stream" ? "event-source" : "effect",
    treatment: operation.kind === "stream" ? "wrapped-as-scoped-stream" : "wrapped",
    platforms: operation.platforms,
    coverage: {
      declaration: "complete",
      adapter: operation.evidence.adapter,
      scenario: operation.evidence.scenario,
      ...platformCoverage(operation.platforms, "unverified"),
      agent: "unverified"
    }
  }))
  const unimplemented = spec.native.unimplementedOperations.map((operation) => {
    const derived = operation.treatment === "derive-from-service"
    return {
      upstream: operation.upstream,
      effect: null,
      kind: operation.kind,
      treatment: operation.treatment,
      platforms: operation.platforms,
      coverage: {
        declaration: derived ? "not-applicable" : "missing",
        adapter: derived ? "not-applicable" : "missing",
        scenario: derived ? "not-applicable" : "missing",
        ...platformCoverage(operation.platforms, derived ? "unverified" : "missing"),
        agent: derived ? "unverified" : "missing"
      }
    }
  })

  return `// This file is generated by \`effect-expo generate\`. Do not edit it by hand.

export const NetworkCapability = ${JSON.stringify(
    { classification: "native-capability", operations: [...implemented, ...unimplemented] },
    null,
    2
  )} as const
`
}

export const generateNetwork = Effect.gen(function* () {
  const spec = yield* readSpec
  yield* Effect.all(
    [
      writeGeneratedArtifact(networkOutputPath, renderNetwork(spec)),
      writeGeneratedArtifact(networkCapabilityOutputPath, renderNetworkCapability(spec))
    ],
    { discard: true }
  )
})

export const checkNetworkOutput = (
  spec: CapabilitySpec,
  actual: string | undefined,
  path = networkOutputPath
) =>
  actual === renderNetwork(spec)
    ? Effect.void
    : Effect.fail(new GeneratedArtifactOutOfDate({ paths: [path] }))

export const checkNetworkArtifacts = (
  spec: CapabilitySpec,
  network: string | undefined,
  capability: string | undefined
) => {
  const paths = [
    ...(network === renderNetwork(spec) ? [] : [networkOutputPath]),
    ...(capability === renderNetworkCapability(spec) ? [] : [networkCapabilityOutputPath])
  ]
  return paths.length === 0 ? Effect.void : Effect.fail(new GeneratedArtifactOutOfDate({ paths }))
}

export const checkNetwork = Effect.gen(function* () {
  const spec = yield* readSpec
  const [network, capability] = yield* Effect.all([
    readGeneratedArtifact(networkOutputPath),
    readGeneratedArtifact(networkCapabilityOutputPath)
  ])
  yield* checkNetworkArtifacts(spec, network, capability)
})
