// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-task-manager at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoTaskManager from "expo-task-manager"

export const defineTask: typeof ExpoTaskManager.defineTask = ExpoTaskManager.defineTask
export const getRegisteredTasksAsync: typeof ExpoTaskManager.getRegisteredTasksAsync =
  ExpoTaskManager.getRegisteredTasksAsync
export const getTaskOptionsAsync: typeof ExpoTaskManager.getTaskOptionsAsync =
  ExpoTaskManager.getTaskOptionsAsync
export const isAvailableAsync: typeof ExpoTaskManager.isAvailableAsync =
  ExpoTaskManager.isAvailableAsync
export const isTaskDefined: typeof ExpoTaskManager.isTaskDefined = ExpoTaskManager.isTaskDefined
export const isTaskRegisteredAsync: typeof ExpoTaskManager.isTaskRegisteredAsync =
  ExpoTaskManager.isTaskRegisteredAsync
export const unregisterAllTasksAsync: typeof ExpoTaskManager.unregisterAllTasksAsync =
  ExpoTaskManager.unregisterAllTasksAsync
export const unregisterTaskAsync: typeof ExpoTaskManager.unregisterTaskAsync =
  ExpoTaskManager.unregisterTaskAsync

export type RegisteredTask = ExpoTaskManager.RegisteredTask
export type TaskManagerError = ExpoTaskManager.TaskManagerError
export type TaskManagerTask = ExpoTaskManager.TaskManagerTask
export type TaskManagerTaskBody<T = unknown> = ExpoTaskManager.TaskManagerTaskBody<T>
export type TaskManagerTaskBodyExecutionInfo = ExpoTaskManager.TaskManagerTaskBodyExecutionInfo
export type TaskManagerTaskExecutor<T = any> = ExpoTaskManager.TaskManagerTaskExecutor<T>
