// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-sqlite at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoSqlite from "expo-sqlite"

export const SQLiteDatabase: typeof ExpoSqlite.SQLiteDatabase = ExpoSqlite.SQLiteDatabase
export const SQLiteProvider: typeof ExpoSqlite.SQLiteProvider = ExpoSqlite.SQLiteProvider
export const SQLiteSession: typeof ExpoSqlite.SQLiteSession = ExpoSqlite.SQLiteSession
export const SQLiteStatement: typeof ExpoSqlite.SQLiteStatement = ExpoSqlite.SQLiteStatement
export const SQLiteTaggedQuery: typeof ExpoSqlite.SQLiteTaggedQuery = ExpoSqlite.SQLiteTaggedQuery
export const addDatabaseChangeListener: typeof ExpoSqlite.addDatabaseChangeListener =
  ExpoSqlite.addDatabaseChangeListener
export const backupDatabaseAsync: typeof ExpoSqlite.backupDatabaseAsync =
  ExpoSqlite.backupDatabaseAsync
export const backupDatabaseSync: typeof ExpoSqlite.backupDatabaseSync =
  ExpoSqlite.backupDatabaseSync
export const bundledExtensions: typeof ExpoSqlite.bundledExtensions = ExpoSqlite.bundledExtensions
export const deepEqual: typeof ExpoSqlite.deepEqual = ExpoSqlite.deepEqual
export const defaultDatabaseDirectory: typeof ExpoSqlite.defaultDatabaseDirectory =
  ExpoSqlite.defaultDatabaseDirectory
export const deleteDatabaseAsync: typeof ExpoSqlite.deleteDatabaseAsync =
  ExpoSqlite.deleteDatabaseAsync
export const deleteDatabaseSync: typeof ExpoSqlite.deleteDatabaseSync =
  ExpoSqlite.deleteDatabaseSync
export const deserializeDatabaseAsync: typeof ExpoSqlite.deserializeDatabaseAsync =
  ExpoSqlite.deserializeDatabaseAsync
export const deserializeDatabaseSync: typeof ExpoSqlite.deserializeDatabaseSync =
  ExpoSqlite.deserializeDatabaseSync
export const importDatabaseFromAssetAsync: typeof ExpoSqlite.importDatabaseFromAssetAsync =
  ExpoSqlite.importDatabaseFromAssetAsync
export const openDatabaseAsync: typeof ExpoSqlite.openDatabaseAsync = ExpoSqlite.openDatabaseAsync
export const openDatabaseSync: typeof ExpoSqlite.openDatabaseSync = ExpoSqlite.openDatabaseSync
export const useSQLiteContext: typeof ExpoSqlite.useSQLiteContext = ExpoSqlite.useSQLiteContext

export type Changeset = ExpoSqlite.Changeset
export type DatabaseChangeEvent = ExpoSqlite.DatabaseChangeEvent
export type SQLiteBindParams = ExpoSqlite.SQLiteBindParams
export type SQLiteBindValue = ExpoSqlite.SQLiteBindValue
export type SQLiteExecuteAsyncResult<T> = ExpoSqlite.SQLiteExecuteAsyncResult<T>
export type SQLiteExecuteSyncResult<T> = ExpoSqlite.SQLiteExecuteSyncResult<T>
export type SQLiteOpenOptions = ExpoSqlite.SQLiteOpenOptions
export type SQLiteProviderAssetSource = ExpoSqlite.SQLiteProviderAssetSource
export type SQLiteProviderProps = ExpoSqlite.SQLiteProviderProps
export type SQLiteRunResult = ExpoSqlite.SQLiteRunResult
export type SQLiteVariadicBindParams = ExpoSqlite.SQLiteVariadicBindParams
