// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-battery at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoBattery from "expo-battery"

export const BatteryState = ExpoBattery.BatteryState
export const addBatteryLevelListener = ExpoBattery.addBatteryLevelListener
export const addBatteryStateListener = ExpoBattery.addBatteryStateListener
export const addLowPowerModeListener = ExpoBattery.addLowPowerModeListener
export const getBatteryLevelAsync = ExpoBattery.getBatteryLevelAsync
export const getBatteryStateAsync = ExpoBattery.getBatteryStateAsync
export const getPowerStateAsync = ExpoBattery.getPowerStateAsync
export const isAvailableAsync = ExpoBattery.isAvailableAsync
export const isBatteryOptimizationEnabledAsync = ExpoBattery.isBatteryOptimizationEnabledAsync
export const isLowPowerModeEnabledAsync = ExpoBattery.isLowPowerModeEnabledAsync
export const useBatteryLevel = ExpoBattery.useBatteryLevel
export const useBatteryState = ExpoBattery.useBatteryState
export const useLowPowerMode = ExpoBattery.useLowPowerMode
export const usePowerState = ExpoBattery.usePowerState

export type BatteryLevelEvent = ExpoBattery.BatteryLevelEvent
export type BatteryState = ExpoBattery.BatteryState
export type BatteryStateEvent = ExpoBattery.BatteryStateEvent
export type PowerModeEvent = ExpoBattery.PowerModeEvent
export type PowerState = ExpoBattery.PowerState
export type Subscription = ExpoBattery.Subscription
