// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-secure-store at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoSecureStore from "expo-secure-store"

export const AFTER_FIRST_UNLOCK = ExpoSecureStore.AFTER_FIRST_UNLOCK
export const AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY =
  ExpoSecureStore.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY
export const ALWAYS = ExpoSecureStore.ALWAYS
export const ALWAYS_THIS_DEVICE_ONLY = ExpoSecureStore.ALWAYS_THIS_DEVICE_ONLY
export const WHEN_PASSCODE_SET_THIS_DEVICE_ONLY = ExpoSecureStore.WHEN_PASSCODE_SET_THIS_DEVICE_ONLY
export const WHEN_UNLOCKED = ExpoSecureStore.WHEN_UNLOCKED
export const WHEN_UNLOCKED_THIS_DEVICE_ONLY = ExpoSecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY
export const canUseBiometricAuthentication = ExpoSecureStore.canUseBiometricAuthentication
export const deleteItemAsync = ExpoSecureStore.deleteItemAsync
export const getItem = ExpoSecureStore.getItem
export const getItemAsync = ExpoSecureStore.getItemAsync
export const isAvailableAsync = ExpoSecureStore.isAvailableAsync
export const setItem = ExpoSecureStore.setItem
export const setItemAsync = ExpoSecureStore.setItemAsync

export type KeychainAccessibilityConstant = ExpoSecureStore.KeychainAccessibilityConstant
export type SecureStoreOptions = ExpoSecureStore.SecureStoreOptions
