// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-keep-awake at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoKeepAwake from "expo-keep-awake"

export const ExpoKeepAwakeTag: typeof ExpoKeepAwake.ExpoKeepAwakeTag =
  ExpoKeepAwake.ExpoKeepAwakeTag
export const KeepAwakeEventState: typeof ExpoKeepAwake.KeepAwakeEventState =
  ExpoKeepAwake.KeepAwakeEventState
export const activateKeepAwake: typeof ExpoKeepAwake.activateKeepAwake =
  ExpoKeepAwake.activateKeepAwake
export const activateKeepAwakeAsync: typeof ExpoKeepAwake.activateKeepAwakeAsync =
  ExpoKeepAwake.activateKeepAwakeAsync
export const addListener: typeof ExpoKeepAwake.addListener = ExpoKeepAwake.addListener
export const deactivateKeepAwake: typeof ExpoKeepAwake.deactivateKeepAwake =
  ExpoKeepAwake.deactivateKeepAwake
export const isAvailableAsync: typeof ExpoKeepAwake.isAvailableAsync =
  ExpoKeepAwake.isAvailableAsync
export const useKeepAwake: typeof ExpoKeepAwake.useKeepAwake = ExpoKeepAwake.useKeepAwake

export type KeepAwakeEvent = ExpoKeepAwake.KeepAwakeEvent
export type KeepAwakeEventState = ExpoKeepAwake.KeepAwakeEventState
export type KeepAwakeListener = ExpoKeepAwake.KeepAwakeListener
export type KeepAwakeOptions = ExpoKeepAwake.KeepAwakeOptions
