// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-keep-awake at Expo 534c99966e34580f56242eb92aac7689b9089cc7

import * as ExpoKeepAwake from "expo-keep-awake"

export const ExpoKeepAwakeTag = ExpoKeepAwake.ExpoKeepAwakeTag
export const KeepAwakeEventState = ExpoKeepAwake.KeepAwakeEventState
export const activateKeepAwake = ExpoKeepAwake.activateKeepAwake
export const activateKeepAwakeAsync = ExpoKeepAwake.activateKeepAwakeAsync
export const addListener = ExpoKeepAwake.addListener
export const deactivateKeepAwake = ExpoKeepAwake.deactivateKeepAwake
export const isAvailableAsync = ExpoKeepAwake.isAvailableAsync
export const useKeepAwake = ExpoKeepAwake.useKeepAwake

export type KeepAwakeEvent = ExpoKeepAwake.KeepAwakeEvent
export type KeepAwakeEventState = ExpoKeepAwake.KeepAwakeEventState
export type KeepAwakeListener = ExpoKeepAwake.KeepAwakeListener
export type KeepAwakeOptions = ExpoKeepAwake.KeepAwakeOptions
