// @generated by better-native compatibility harness
// Do not edit manually.
// Source: expo-location at Expo 534c99966e34580f56242eb92aac7689b9089cc7
/* oxlint-disable no-underscore-dangle -- exact Expo compatibility exports */

import * as ExpoLocation from "expo-location"

export const Accuracy: typeof ExpoLocation.Accuracy = ExpoLocation.Accuracy
export const ActivityType: typeof ExpoLocation.ActivityType = ExpoLocation.ActivityType
export const EventEmitter: typeof ExpoLocation.EventEmitter = ExpoLocation.EventEmitter
export const GeofencingEventType: typeof ExpoLocation.GeofencingEventType =
  ExpoLocation.GeofencingEventType
export const GeofencingRegionState: typeof ExpoLocation.GeofencingRegionState =
  ExpoLocation.GeofencingRegionState
export const LocationAccuracy: typeof ExpoLocation.LocationAccuracy = ExpoLocation.LocationAccuracy
export const LocationActivityType: typeof ExpoLocation.LocationActivityType =
  ExpoLocation.LocationActivityType
export const LocationGeofencingEventType: typeof ExpoLocation.LocationGeofencingEventType =
  ExpoLocation.LocationGeofencingEventType
export const LocationGeofencingRegionState: typeof ExpoLocation.LocationGeofencingRegionState =
  ExpoLocation.LocationGeofencingRegionState
export const MotionActivityConfidence: typeof ExpoLocation.MotionActivityConfidence =
  ExpoLocation.MotionActivityConfidence
export const MotionActivityType: typeof ExpoLocation.MotionActivityType =
  ExpoLocation.MotionActivityType
export const PermissionStatus: typeof ExpoLocation.PermissionStatus = ExpoLocation.PermissionStatus
export const _getCurrentWatchId: typeof ExpoLocation._getCurrentWatchId =
  ExpoLocation._getCurrentWatchId
export const enableNetworkProviderAsync: typeof ExpoLocation.enableNetworkProviderAsync =
  ExpoLocation.enableNetworkProviderAsync
export const geocodeAsync: typeof ExpoLocation.geocodeAsync = ExpoLocation.geocodeAsync
export const getBackgroundPermissionsAsync: typeof ExpoLocation.getBackgroundPermissionsAsync =
  ExpoLocation.getBackgroundPermissionsAsync
export const getCurrentPositionAsync: typeof ExpoLocation.getCurrentPositionAsync =
  ExpoLocation.getCurrentPositionAsync
export const getForegroundPermissionsAsync: typeof ExpoLocation.getForegroundPermissionsAsync =
  ExpoLocation.getForegroundPermissionsAsync
export const getHeadingAsync: typeof ExpoLocation.getHeadingAsync = ExpoLocation.getHeadingAsync
export const getLastKnownPositionAsync: typeof ExpoLocation.getLastKnownPositionAsync =
  ExpoLocation.getLastKnownPositionAsync
export const getMotionActivityAsync: typeof ExpoLocation.getMotionActivityAsync =
  ExpoLocation.getMotionActivityAsync
export const getMotionActivityPermissionsAsync: typeof ExpoLocation.getMotionActivityPermissionsAsync =
  ExpoLocation.getMotionActivityPermissionsAsync
export const getProviderStatusAsync: typeof ExpoLocation.getProviderStatusAsync =
  ExpoLocation.getProviderStatusAsync
export const hasServicesEnabledAsync: typeof ExpoLocation.hasServicesEnabledAsync =
  ExpoLocation.hasServicesEnabledAsync
export const hasStartedGeofencingAsync: typeof ExpoLocation.hasStartedGeofencingAsync =
  ExpoLocation.hasStartedGeofencingAsync
export const hasStartedLocationUpdatesAsync: typeof ExpoLocation.hasStartedLocationUpdatesAsync =
  ExpoLocation.hasStartedLocationUpdatesAsync
export const installWebGeolocationPolyfill: typeof ExpoLocation.installWebGeolocationPolyfill =
  ExpoLocation.installWebGeolocationPolyfill
export const isBackgroundLocationAvailableAsync: typeof ExpoLocation.isBackgroundLocationAvailableAsync =
  ExpoLocation.isBackgroundLocationAvailableAsync
export const requestBackgroundPermissionsAsync: typeof ExpoLocation.requestBackgroundPermissionsAsync =
  ExpoLocation.requestBackgroundPermissionsAsync
export const requestForegroundPermissionsAsync: typeof ExpoLocation.requestForegroundPermissionsAsync =
  ExpoLocation.requestForegroundPermissionsAsync
export const requestMotionActivityPermissionsAsync: typeof ExpoLocation.requestMotionActivityPermissionsAsync =
  ExpoLocation.requestMotionActivityPermissionsAsync
export const reverseGeocodeAsync: typeof ExpoLocation.reverseGeocodeAsync =
  ExpoLocation.reverseGeocodeAsync
export const startGeofencingAsync: typeof ExpoLocation.startGeofencingAsync =
  ExpoLocation.startGeofencingAsync
export const startLocationUpdatesAsync: typeof ExpoLocation.startLocationUpdatesAsync =
  ExpoLocation.startLocationUpdatesAsync
export const stopGeofencingAsync: typeof ExpoLocation.stopGeofencingAsync =
  ExpoLocation.stopGeofencingAsync
export const stopLocationUpdatesAsync: typeof ExpoLocation.stopLocationUpdatesAsync =
  ExpoLocation.stopLocationUpdatesAsync
export const useBackgroundPermissions: typeof ExpoLocation.useBackgroundPermissions =
  ExpoLocation.useBackgroundPermissions
export const useForegroundPermissions: typeof ExpoLocation.useForegroundPermissions =
  ExpoLocation.useForegroundPermissions
export const useMotionActivityPermissions: typeof ExpoLocation.useMotionActivityPermissions =
  ExpoLocation.useMotionActivityPermissions
export const watchHeadingAsync: typeof ExpoLocation.watchHeadingAsync =
  ExpoLocation.watchHeadingAsync
export const watchMotionActivityAsync: typeof ExpoLocation.watchMotionActivityAsync =
  ExpoLocation.watchMotionActivityAsync
export const watchPositionAsync: typeof ExpoLocation.watchPositionAsync =
  ExpoLocation.watchPositionAsync

export type Accuracy = ExpoLocation.Accuracy
export type ActivityType = ExpoLocation.ActivityType
export type EventEmitter = typeof ExpoLocation.EventEmitter
export type GeofencingEventType = ExpoLocation.GeofencingEventType
export type GeofencingRegionState = ExpoLocation.GeofencingRegionState
export type LocationAccuracy = ExpoLocation.LocationAccuracy
export type LocationActivityType = ExpoLocation.LocationActivityType
export type LocationCallback = ExpoLocation.LocationCallback
export type LocationErrorCallback = ExpoLocation.LocationErrorCallback
export type LocationGeocodedAddress = ExpoLocation.LocationGeocodedAddress
export type LocationGeocodedLocation = ExpoLocation.LocationGeocodedLocation
export type LocationGeofencingEventType = ExpoLocation.LocationGeofencingEventType
export type LocationGeofencingRegionState = ExpoLocation.LocationGeofencingRegionState
export type LocationHeadingCallback = ExpoLocation.LocationHeadingCallback
export type LocationHeadingObject = ExpoLocation.LocationHeadingObject
export type LocationLastKnownOptions = ExpoLocation.LocationLastKnownOptions
export type LocationObject = ExpoLocation.LocationObject
export type LocationObjectCoords = ExpoLocation.LocationObjectCoords
export type LocationOptions = ExpoLocation.LocationOptions
export type LocationPermissionResponse = ExpoLocation.LocationPermissionResponse
export type LocationProviderStatus = ExpoLocation.LocationProviderStatus
export type LocationRegion = ExpoLocation.LocationRegion
export type LocationSubscription = ExpoLocation.LocationSubscription
export type LocationTaskOptions = ExpoLocation.LocationTaskOptions
export type LocationTaskServiceOptions = ExpoLocation.LocationTaskServiceOptions
export type MotionActivityCallback = ExpoLocation.MotionActivityCallback
export type MotionActivityConfidence = ExpoLocation.MotionActivityConfidence
export type MotionActivityObject = ExpoLocation.MotionActivityObject
export type MotionActivityState = ExpoLocation.MotionActivityState
export type MotionActivityType = ExpoLocation.MotionActivityType
export type PermissionDetailsLocationAndroid = ExpoLocation.PermissionDetailsLocationAndroid
export type PermissionDetailsLocationIOS = ExpoLocation.PermissionDetailsLocationIOS
export type PermissionExpiration = ExpoLocation.PermissionExpiration
export type PermissionHookOptions<Options extends object> =
  ExpoLocation.PermissionHookOptions<Options>
export type PermissionResponse = ExpoLocation.PermissionResponse
export type PermissionStatus = ExpoLocation.PermissionStatus
